# Generated by Django 4.0 on 2021-12-25 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("authors", "0002_remove_author_id_author_uuid")]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("7dc10fb3-67e4-4526-97f0-b36adcd10081"), primary_key=True, serialize=False
            ),
        )
    ]
