# Generated by Django 4.0 on 2021-12-29 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("authors", "0004_alter_author_uuid")]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("43f80af3-3e94-4969-98d6-5e9ebe7c76b0"), primary_key=True, serialize=False
            ),
        )
    ]
