# Generated by Django 4.0 on 2021-12-29 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("4954d652-2da0-4ceb-a454-3a2c06579bca"), primary_key=True, serialize=False
                    ),
                ),
                ("user_name", models.CharField(max_length=64)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        )
    ]
